version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ~/.ssh:/root/.ssh
    links:
      - postgres
    environment:
      DJANGO_SETTINGS_MODULE: settings
    command: ./wait-for-it.sh postgres:5432 --timeout=60 -- ./manage.py runserver  0.0.0.0:80

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: g_write
      POSTGRES_DB: citest
    ports:
      - "5432:5432"
